package com.snaps.common.utils.image;

/**
 * Created by ysjeong on 2017. 8. 31..
 */

public interface ResolutionConstants {
    int NO_PRINT_TOAST_OFFSETX_BASIC = 0;
    int NO_PRINT_TOAST_OFFSETY_BASIC = 12;
    int NO_PRINT_TOAST_OFFSETX_PHOTOPRINT_EDIT = 0;
    int NO_PRINT_TOAST_OFFSETY_PHOTOPRINT_EDIT = 76;
    int NO_PRINT_TOAST_OFFSETX_PRINT_EDIT = 0;
    int NO_PRINT_TOAST_OFFSETY_PRINT_EDIT = 60;
    int NO_PRINT_TOAST_OFFSETY_SMART_RECOMMEND_BOOK_EDIT = 180;
    int NO_PRINT_TOAST_OFFSETX_LANDSCAPE_PRINT_EDIT = 28;
    int NO_PRINT_TOAST_OFFSETY_LANDSCAPE_PRINT_EDIT = 12;

    int NO_PRINT_TOAST_OFFSETX = 0;
    int NO_PRINT_TOAST_OFFSETY = 92;
    int NO_PRINT_TOAST_OFFSETX_LANDSCAPE = 50;
    int NO_PRINT_TOAST_OFFSETY_LANDSCAPE = 12;
    int NO_PRINT_TOAST_OFFSETX_PHOTOCARD = 0;
    int NO_PRINT_TOAST_OFFSETY_PHOTOCARD = 144;
    int NO_PRINT_TOAST_OFFSETX_LANDSCAPE_PHOTOCARD = 75;
    int NO_PRINT_TOAST_OFFSETY_LANDSCAPE_PHOTOCARD = 12;

    float ENABLE_SIZE = 38.9f;
    float MARVEL_FRAME_ENABLE_SIZE = 58.9f;

    float PRINT_SIZE = 54.9f;
    float PICTURE_PRINT_SIZE_3X5 = 51.9f;
    float PICTURE_PRINT_SIZE = 69.9f;
    float PRINT_FABRIC = 39.9f;     //2020년 2웡 25일 작성 : 확인 결과 기본값이 40이라고 한다. 그런데 왜 54.9는 어디서 튀어 나온것일까?, 그리고 인터페이스에 왜 상수를 정의...
}
