package com.snaps.mobile.tutorial;

/**
 * Created by ysjeong on 2017. 7. 31..
 */

public interface SnapsTutorialConstants {
	enum eTUTORIAL_VIEW_DIRECTION {
		ABOVE_OF_VIEW,
		LEFT_OF_VIEW,
		RIGHT_OF_VIEW,
		BELOW_OF_VIEW,
	}

	enum eTUTORIAL_ID {
		TUTORIAL_ID_TOOLTIP_PHOTO_CARD_CHANGE_DESIGN,
		TUTORIAL_ID_TOOLTIP_PHOTO_CARD_LONG_CLICK_DELETE,
		TUTORIAL_ID_TOOLTIP_PHOTO_CARD_CHANGE_QUANTITY,
		TUTORIAL_ID_TOOLTIP_WALLET_PHOTO_CHANGE_DESIGN,
		TUTORIAL_ID_TOOLTIP_RENEWAL,
		TUTORIAL_ID_TOAST_REMOVE_POST,
		TUTORIAL_ID_PHOTOBOOK_FIND_COVER,
		TUTORIAL_ID_SNSBOOK_FIND_COVER,
		TUTORIAL_ID_TOOLTIP_NEW_YEARS_CARD_CHANGE_QUANTITY,
		TUTORIAL_ID_TOOLTIP_NEW_YEARS_CARD_LONG_CLICK_DELETE,
		TUTORIAL_ID_TOOLTIP_TEXT_EDIT_TUTORIAL,
		TUTORIAL_ID_TOOLTIP_NAME_STICKER_TEXT_EDIT_TUTORIAL,
		TUTORIAL_ID_TOOLTIP_NAME_ACRYLIC_KEYRING_TOUCH_UPLOAD_PNG_FILE,
		TUTORIAL_ID_TOOLTIP_NAME_ACRYLIC_STAND_TOUCH_UPLOAD_PNG_FILE,
	}

	enum eTUTORIAL_VIEW_POSITION {
		TOP,
		CENTER,
		BOTTOM,
		TOAST_POSITION,
		SMART_RECOMMEND_BOOK_MAIN_PAGE_COVER,
		BOOK_ITEM,
		BOOK_ITEM_LANDSCAPE_WITH_THUMNAILBAR,
		BOTTOM_NOT_TAIL,
		ACCORDION_CARD,
		ACCORDION_CARD_LANDSCAPE
	}

	eTUTORIAL_ID[] BLOCK_TUTORIAL_IDS = {
			eTUTORIAL_ID.TUTORIAL_ID_TOOLTIP_PHOTO_CARD_CHANGE_QUANTITY
	};

	int DEFAULT_TOOLTIP_HEIGHT = 30;
}
