package com.snaps.mobile.activity.book;

public interface IStoryBookTemplateConst {

	/**
	 * Common
	 */
	float STYLE_COMMON_PAGE2_FONTSIZE_DATE = 11;
	float STYLE_COMMON_PAGE2_FONTSIZE_TIME = 6.5f;
	float STYLE_COMMON_PAGE2_FONTSIZE_NOTE = 8;

	float STYLE_COMMON_PAGE2_FONTSIZE_FEELCOUNT = 7;
	float STYLE_COMMON_PAGE2_FONTSIZE_REPLYCOUNT = 7;
	float STYLE_COMMON_PAGE2_FONTSIZE_ETC = 6;

	float STYLE_COMMON_PAGE2_FONTSIZE_REPLYER = 6;
	float STYLE_COMMON_PAGE2_FONTSIZE_REPLYCONTENT = 6;

	/**
	 * One Style
	 */
	byte TABLE_CONTENTS_POS_YEAR = 0;
	byte TABLE_CONTENTS_POS_MONTH = 1;

	int STYLE_1TH_COVER_IDX_SPINE = 0;
	int STYLE_1TH_COVER_IDX_BIRTH = 0;
	int STYLE_1TH_COVER_IDX_NAME = 1;
	int STYLE_1TH_COVER_IDX_TITLE = 2;
	int STYLE_1TH_COVER_IDX_PERIOD = 3;

	int STYLE_1TH_TABLE_CONTENTS_IDX_PERIOD = 16;
	int STYLE_1TH_TABLE_CONTENTS_IDX_MY_KAKAO_STORY = 17;
	int STYLE_1TH_TABLE_CONTENTS_IDX_NAME = 3;

	int[] STYLE_1TH_TABLE_CONTENTS_IDX_YEARS = {12, 13, 14, 15};
	int[] STYLE_1TH_TABLE_CONTENTS_IDX_MONTHS = {4, 11, 10, 9, 8, 7, 6, 5};

	int STYLE_1TH_THEME_PHOTO_IDX = 32;
	int STYLE_1TH_THEME_NAME_IDX = 2;

	int STYLE_1TH_PAGE_IDX_PERIOD_STR = 0;
	int STYLE_1TH_PAGE_IDX_LEFT_YEARS = 1;
	int STYLE_1TH_PAGE_IDX_DATE = 2;
	int STYLE_1TH_PAGE_IDX_TIME = 3;
	int STYLE_1TH_PAGE_IDX_CONTENTS = 4;
	int STYLE_1TH_PAGE_IDX_FEEL_CNT = 5;
	int STYLE_1TH_PAGE_IDX_COMMENT_CNT = 6;
	int STYLE_1TH_PAGE_IDX_ETC = 7;
	int STYLE_1TH_PAGE_IDX_COMMENT_ACTOR_01 = 8;
	int STYLE_1TH_PAGE_IDX_COMMENT_CONTENTS_01 = 9;
	int STYLE_1TH_PAGE_IDX_RIGHT_YEARS = 10;

	int STYLE_1TH_PAGE2_STICKER_IDX_CHAPTER_ARROW = 1;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_HEART = 2;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_BALLON = 3;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_LIKE = 4;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_CHEERUP = 5;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_HAPPY = 6;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_SAD = 7;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_COOL = 8;
	int STYLE_1TH_PAGE2_STICKER_IDX_FEEL_ETC = 9;
	int STYLE_1TH_PAGE2_STICKER_IDX_LINE_1 = 10;
	int STYLE_1TH_PAGE2_STICKER_IDX_LINE_2 = 11;
	int STYLE_1TH_PAGE2_STICKER_IDX_DEFAULT_PROFILE = 12;

	int STYLE_1TH_PAGE2_IMAGE_IDX_POST_PHOTO = 3;
	int STYLE_1TH_PAGE2_IMAGE_IDX_FEEL_PROFILE = 4;
	// 챕터에 들어가는 이미지 인덱스
	int STYLE_1TH_PAGE2_IMAGE_IDX_CHAPTER_PHOTO1 = 0;
	int STYLE_1TH_PAGE2_IMAGE_IDX_CHAPTER_PHOTO2 = 1;
	int STYLE_1TH_PAGE2_IMAGE_IDX_CHAPTER_PHOTO3 = 2;

	// fontSize
	float STYLE_1TH_COVER_FONTSIZE_SPINE = 14;
	float STYLE_1TH_COVER_FONTSIZE_TITLE = 24;
	float STYLE_1TH_COVER_FONTSIZE_BIRTH_DATE = 12;
	float STYLE_1TH_COVER_FONTSIZE_USER_NAME = 25;
	float STYLE_1TH_COVER_FONTSIZE_PERIOD = 20;

	float STYLE_1TH_INDEX_FONTSIZE_PERIOD = 28;
	float STYLE_1TH_INDEX_FONTSIZE_USER_NAME = 20;
	float STYLE_1TH_INDEX_FONTSIZE_YEARS = 17;
	float STYLE_1TH_INDEX_FONTSIZE_MONTH = 13;

	float STYLE_1TH_TITLE_FONTSIZE_USER_NAME = 18;

	float STYLE_1TH_PAGE_FONTSIZE_CHATER_PERIOD = 32;
	float STYLE_1TH_PAGE_FONTSIZE_RIGHT_YEAR = 7;

	/**
	 * A Style
	 */
	float STYLE_ATH_PAGE_FONTSIZE_CHATER_PERIOD = 32;
	float STYLE_ATH_PAGE_FONTSIZE_CHATER_YEAR = 38;
	int STYLE_ATH_PAGE2_IMAGE_IDX_POST_PHOTO = 0;
	int STYLE_ATH_PAGE2_IMAGE_IDX_FEEL_PROFILE = 1;
	int STYLE_ATH_PAGE2_STICKER_IDX_CHAPTER_ARROW = 0;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_HEART = 1;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_BALLON = 2;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_LIKE = 3;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_CHEERUP = 4;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_HAPPY = 5;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_SAD = 6;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_COOL = 7;
	int STYLE_ATH_PAGE2_STICKER_IDX_FEEL_ETC = 8;
	int STYLE_ATH_PAGE2_STICKER_IDX_LINE_1 = 9;
	int STYLE_ATH_PAGE2_STICKER_IDX_LINE_2 = 10;
	int STYLE_ATH_PAGE2_STICKER_IDX_DEFAULT_PROFILE = 11;
	/**
	 * Two Style
	 */
	int[] STYLE_2TH_TABLE_CONTENTS_IDX_YEARS = {0, 17, 18, 21, 34};
	int[] STYLE_2TH_TABLE_CONTENTS_IDX_MONTHS = {1, 15, 13, 11, 9, 7, 5, 3, 19, 32, 30, 28, 26, 24, 22};

	int STYLE_2TH_COVER_IDX_SPINE = 0;
	int STYLE_2TH_COVER_IDX_PROFILE = 0;
	int STYLE_2TH_COVER_IDX_PERIOD = 1;

	int STYLE_2TH_TITLE_IDX_PROFILE = 19;
	int STYLE_2TH_TITLE_IDX_FRIEND_CNT = 11;
	int STYLE_2TH_TITLE_IDX_FEEL_CNT = 12;
	int STYLE_2TH_TITLE_IDX_COMMENT_CNT = 13;
	int STYLE_2TH_TITLE_IDX_FEEL_N_COMMENT_CNT = 14;
	int STYLE_2TH_TITLE_IDX_STORY_CNT = 15;
	int STYLE_2TH_TITLE_IDX_PHOTO_CNT = 16;
	int STYLE_2TH_TITLE_IDX_STORY_N_PHOTO_CNT = 17;
	int STYLE_2TH_TITLE_IDX_STORY_TOTAL_CNT = 18;

	int STYLE_2TH_PAGE_IDX_MONTH_N_YEAR = 0;
	int STYLE_2TH_PAGE_IDX_CHAPTER_NUM = 1;
	int STYLE_2TH_PAGE_IDX_DATE_LEFT = 2;
	int STYLE_2TH_PAGE_IDX_DATE_RIGHT = 3;
	int STYLE_2TH_PAGE_IDX_CONTENTS_LINE_01 = 4;
	int STYLE_2TH_PAGE_IDX_CONTENTS_LINE_02 = 5;
	int STYLE_2TH_PAGE_IDX_FEEL_CNT = 5;
	int STYLE_2TH_PAGE_IDX_REPLY_CNT = 6;
	// int STYLE_2TH_PAGE_IDX_REPLY_WRITER_01 = 9;
	// int STYLE_2TH_PAGE_IDX_REPLY_CONTENTS_01 = 10;
	// int STYLE_2TH_PAGE_IDX_REPLY_WRITER_02 = 11;
	// int STYLE_2TH_PAGE_IDX_REPLY_CONTENTS_02 = 12;
	int STYLE_2TH_PAGE_IDX_YEARS = 13;
	int STYLE_2TH_PAGE_IDX_MONTH = 12;

	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_HEART = 0;
	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_BALLON = 1;
	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_LIKE = 2;
	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_CHEERUP = 3;
	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_HAPPY = 4;
	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_SAD = 5;
	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_COOL = 6;

	int STYLE_2TH_PAGE2_STICKER_IDX_FEEL_ETC = 7;
	int STYLE_2TH_PAGE2_STICKER_IDX_LINE_1 = 8;
	int STYLE_2TH_PAGE2_STICKER_IDX_LINE_2 = 9;
	int STYLE_2TH_PAGE2_STICKER_IDX_DATE_BG = 10;
	int STYLE_2TH_PAGE2_STICKER_IDX_DEFAULT_PROFILE = 11;

	int STYLE_2TH_PAGE2_IMAGE_IDX_POST_PHOTO = 0;
	int STYLE_2TH_PAGE2_IMAGE_IDX_FEEL_PROFILE = 1;

	int STYLE_2TH_PAGE2_TEXT_IDX_DATE = 2;
	int STYLE_2TH_PAGE2_TEXT_IDX_TIME = 3;
	int STYLE_2TH_PAGE2_TEXT_IDX_NOTE = 4;
	int STYLE_2TH_PAGE2_TEXT_IDX_REPLY_WRITER_ETC = 7;
	int STYLE_2TH_PAGE2_TEXT_IDX_REPLY_WRITER = 8;
	int STYLE_2TH_PAGE2_TEXT_IDX_REPLY_CONTENT = 9;

	// fontSize
	float STYLE_2TH_COVER_FONTSIZE_SPINE = 14;
	float STYLE_2TH_COVER_FONTSIZE_TITLE = 20;
	float STYLE_2TH_COVER_FONTSIZE_PERIOD = 30;

	float STYLE_2TH_INDEX_FONTSIZE_YEAR = 28;
	float STYLE_2TH_INDEX_FONTSIZE_MONTH = 15;

	float STYLE_2TH_TITLE_FONTSIZE_LARGE = 55;
	float STYLE_2TH_TITLE_FONTSIZE_SMALL = 35;
	float STYLE_2TH_TITLE_FONTSIZE_PROFILE = 20;

	float STYLE_2TH_PAGE2_CHEPTER_FONTSIZE_INDEX = 65;
	float STYLE_2TH_PAGE2_CHEPTER_FONTSIZE_PERIOD = 24;
	float STYLE_2TH_PAGE2_FONTSIZE_RIGHTYEAR = 8;

	/**
	 * Three Style
	 */
	int STYLE_3TH_COVER_IDX_SPINE = 0;
	int STYLE_3TH_COVER_IDX_TITLE = 0;
	int STYLE_3TH_COVER_IDX_NAME = 1;
	int STYLE_3TH_COVER_IDX_PERIOD = 2;
	int STYLE_3TH_COVER_IDX_BIRTH = 3;

	int STYLE_3TH_TABLE_CONTENTS_IDX_TITLE = 1;
	int[] STYLE_3TH_TABLE_CONTENTS_IDX_YEARS = {2, 5, 4, 3};
	int[] STYLE_3TH_TABLE_CONTENTS_IDX_MONTHS = {6, 9, 13, 12, 11, 10, 8, 7};
	int STYLE_3TH_THEME_PHOTO_IDX = 12;
	int STYLE_3TH_THEME_TEXT_NAME_IDX = 0;
	int STYLE_3TH_THEME_TEXT_PERIOD_IDX = 1;
	int STYLE_3TH_THEME_TEXT_DATE_IDX = 2;
	int STYLE_3TH_THEME_TEXT_DAYOFWEEK_IDX = 5;
	int STYLE_3TH_THEME_TEXT_LIKE_IDX = 3;
	int STYLE_3TH_THEME_TEXT_COMMENT_IDX = 4;

	int STYLE_3TH_PAGE_IDX_PERIOD_STR = 0;
	int STYLE_3TH_PAGE_IDX_MEMORIES = 1;
	int STYLE_3TH_PAGE_IDX_DATE = 2;
	int STYLE_3TH_PAGE_IDX_TIME = 3;
	int STYLE_3TH_PAGE_IDX_CONTENTS = 4;
	int STYLE_3TH_PAGE_IDX_FEEL_CNT = 5;
	int STYLE_3TH_PAGE_IDX_COMMENT_CNT = 6;
	int STYLE_3TH_PAGE_IDX_ETC = 7;
	int STYLE_3TH_PAGE_IDX_COMMENT_ACTOR_01 = 8;
	int STYLE_3TH_PAGE_IDX_COMMENT_CONTENTS_01 = 9;
	int STYLE_3TH_PAGE_IDX_COMMENT_ACTOR_02 = 10;
	int STYLE_3TH_PAGE_IDX_COMMENT_CONTENTS_02 = 11;
	int STYLE_3TH_PAGE_IDX_PERIOD_NUMBER = 12;
	int STYLE_3TH_PAGE_IDX_LEFT_YEARS = 13;
	int STYLE_3TH_PAGE_IDX_RIGHT_YEARS = 14;

	// 챕터에 들어가는 이미지 인덱스
	int STYLE_3TH_PAGE2_IMAGE_IDX_CHAPTER_PHOTO1 = 8;
	int STYLE_3TH_PAGE2_IMAGE_IDX_CHAPTER_PHOTO2 = 9;
	int STYLE_3TH_PAGE2_IMAGE_IDX_CHAPTER_PHOTO3 = 10;

	int STYLE_3TH_PAGE2_STICKER_IDX_DEFAULT_PROFILE = 11;

	// fontSize

	float STYLE_3TH_COVER_FONTSIZE_SPINE = 14;
	float STYLE_3TH_COVER_FONTSIZE_TITLE = 27;
	float STYLE_3TH_COVER_FONTSIZE_BIRTH_DATE = 10;
	float STYLE_3TH_COVER_FONTSIZE_USER_NAME = 19;
	float STYLE_3TH_COVER_FONTSIZE_PERIOD = 21;

	float STYLE_3TH_INDEX_FONTSIZE_YEARS = 11;
	float STYLE_3TH_INDEX_FONTSIZE_MONTH = 9;

	float STYLE_3TH_TITLE_FONTSIZE_USER_NAME = 14;
	float STYLE_3TH_TITLE_FONTSIZE_PERIOD = 13;
	float STYLE_3TH_TITLE_FONTSIZE_S_DAY_DATE = 21;
	float STYLE_3TH_TITLE_FONTSIZE_S_DAY_AM_PM = 11;
	float STYLE_3TH_TITLE_FONTSIZE_S_DAY_TIME = 17;
	float STYLE_3TH_TITLE_FONTSIZE_S_DAY_FEEL_N_COMMENT = 20;

	float STYLE_3TH_PAGE_FONTSIZE_CHATER_PERIOD_STR = 16;
	float STYLE_3TH_PAGE_FONTSIZE_CHATER_PERIOD_NUMBER = 14;
	float STYLE_3TH_PAGE_FONTSIZE_CHATER_STORY_COUNT = 18;
	float STYLE_3TH_PAGE_FONTSIZE_LEFT_YEAR = 11;
	float STYLE_3TH_PAGE_FONTSIZE_RIGHT_YEAR = 9;
	/**
	 * C Style
	 */
	float STYLE_C_PAGE_FONTSIZE_CHATER_PERIOD_NUMBER = 11;
	float STYLE_C_PAGE_FONTSIZE_CHATER_STORY_COUNT = 22;

	/**
	 * Four Style
	 */
	int STYLE_4TH_COVER_IDX_SPINE = 0;
	int STYLE_4TH_COVER_IDX_NAME = 0;
	int STYLE_4TH_COVER_IDX_TITLE = 1;
	int STYLE_4TH_COVER_IDX_PERIOD = 2;
	int STYLE_4TH_COVER_IDX_MONTH_CNT = 3;
	int STYLE_4TH_COVER_IDX_PHOTO_CNT = 4;
	int STYLE_4TH_COVER_IDX_STORY_CNT = 5;
	int STYLE_4TH_COVER_IDX_REPLY_CNT = 6;

	int STYLE_4TH_COVER_IDX_STICKER_COUNTS = 0;
	int STYLE_4TH_COVER_IDX_STICKER_LOGO = 1;
	int STYLE_4TH_COVER_IDX_STICKER_TITLE = 2;

	int[] STYLE_4TH_TABLE_CONTENTS_IDX_CHATER = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
	int[] STYLE_4TH_TABLE_CONTENTS_IDX_PERIOD = {12, 13, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14};

	int STYLE_4TH_THEME_NAME_IDX = 3;
	int STYLE_4TH_THEME_MONTH_CNT_IDX = 0;
	int STYLE_4TH_THEME_LEFT_PHOTO_CNT_IDX = 2;
	int STYLE_4TH_THEME_STORY_CNT_IDX = 1;
	int STYLE_4TH_THEME_LEFT_REPLY_CNT_IDX = 4;
	int STYLE_4TH_THEME_DATE_IDX = 5;
	int STYLE_4TH_THEME_RIGHT_REPLY_CNT_IDX = 6;
	int STYLE_4TH_THEME_FEEL_CNT_IDX = 7;
	int STYLE_4TH_THEME_RIGHT_PHOTO_CNT_IDX = 8;

	int STYLE_4TH_PAGE_IDX_CHATER_NUMBER = 0;
	int STYLE_4TH_PAGE_IDX_CHATER_STICKER_DOT = 10;
	int STYLE_4TH_PAGE_IDX_CHATER_STICKER_STORIES = 11;
	int STYLE_4TH_PAGE_IDX_CHATER_STICKER_PHOTOS = 12;
	int STYLE_4TH_PAGE_IDX_PERIOD_STR = 11;
	int STYLE_4TH_PAGE_IDX_DATE = 1;
	int STYLE_4TH_PAGE_IDX_TIME = 2;
	int STYLE_4TH_PAGE_IDX_CONTENTS = 3;
	int STYLE_4TH_PAGE_IDX_FEEL_CNT = 4;
	int STYLE_4TH_PAGE_IDX_COMMENT_CNT = 5;
	int STYLE_4TH_PAGE_IDX_ETC = 6;
	int STYLE_4TH_PAGE_IDX_COMMENT_ACTOR_01 = 7;
	int STYLE_4TH_PAGE_IDX_COMMENT_CONTENTS_01 = 8;
	int STYLE_4TH_PAGE_IDX_COMMENT_ACTOR_02 = 9;
	int STYLE_4TH_PAGE_IDX_COMMENT_CONTENTS_02 = 10;
	int STYLE_4TH_PAGE_IDX_RIGHT_YEARS = 12;
	int STYLE_4TH_PAGE_IDX_STORY_CNT = 13;
	int STYLE_4TH_PAGE_IDX_PHOTO_CNT = 14;

	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_HEART = 0;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_BALLON = 1;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_LIKE = 2;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_CHEERUP = 3;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_HAPPY = 4;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_SAD = 5;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_COOL = 6;
	int STYLE_4TH_PAGE2_STICKER_IDX_FEEL_ETC = 7;
	int STYLE_4TH_PAGE2_STICKER_IDX_LINE_1 = 8;
	int STYLE_4TH_PAGE2_STICKER_IDX_LINE_2 = 9;
	int STYLE_4TH_PAGE2_STICKER_IDX_POINT = 10;
	int STYLE_4TH_PAGE2_STICKER_IDX_STORIES_TEXT = 11;
	int STYLE_4TH_PAGE2_STICKER_IDX_PHOTOS_TEXT = 12;
	int STYLE_4TH_PAGE2_STICKER_IDX_LINE_3 = 13;
	int STYLE_4TH_PAGE2_STICKER_IDX_DEFAULT_PROFILE = 14;

	int STYLE_4TH_PAGE2_TEXT_IDX_TO_MONTH = 15;
	int STYLE_4TH_PAGE2_TEXT_IDX_FROM_YEAR = 16;
	int STYLE_4TH_PAGE2_TEXT_IDX_TO_YEAR = 17;

	// fontSize
	float STYLE_4TH_COVER_FONTSIZE_SPINE = 14;
	float STYLE_4TH_COVER_FONTSIZE_TITLE = 12;
	float STYLE_4TH_COVER_FONTSIZE_COUNTS = 48;
	float STYLE_4TH_COVER_FONTSIZE_USER_NAME = 16;
	float STYLE_4TH_COVER_FONTSIZE_PERIOD = 12;

	float STYLE_4TH_INDEX_FONTSIZE_YEARS = 12;
	float STYLE_4TH_INDEX_FONTSIZE_MONTH = 10;

	float STYLE_4TH_TITLE_FONTSIZE_USER_NAME = 16;
	float STYLE_4TH_TITLE_FONTSIZE_COUNTS = 49;
	float STYLE_4TH_TITLE_FONTSIZE_S_DAY_DATE = 19;
	float STYLE_4TH_TITLE_FONTSIZE_S_DAY_COUNT = 35;

	float STYLE_4TH_PAGE_FONTSIZE_CHATER_NUMBER = 75;
	float STYLE_4TH_PAGE_FONTSIZE_CHATER_PERIOD = 22;
	float STYLE_4TH_PAGE_FONTSIZE_CHATER_PERIOD_YEAR = 11;
	float STYLE_4TH_PAGE_FONTSIZE_CHATER_COUNT = 28;
	float STYLE_4TH_PAGE_FONTSIZE_RIGHT_YEAR = 8;

}
